//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaCRUD.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int cod_usuario { get; set; }
        public string usuario1 { get; set; }
        public string password { get; set; }
        public string nombre_usuario { get; set; }
        public string apellido_usuario { get; set; }
        public int dni { get; set; }
        public int cod_nacionalidad { get; set; }
    
        public virtual Nacionalidad Nacionalidad { get; set; }
    }
}
